# Generated by Django 4.1.6 on 2023-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_info_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(max_length=255),
        ),
    ]
