# Generated by Django 4.1.6 on 2023-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(default=1, upload_to='color_images/'),
            preserve_default=False,
        ),
    ]
