# Generated by Django 4.1.6 on 2023-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='speciality',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
