# Generated by Django 4.1.6 on 2023-08-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_features_product_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='speciality',
            new_name='specifiactions',
        ),
    ]
