# Generated by Django 4.1.6 on 2023-08-10 16:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_rename_speciality_product_specifiactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifiactions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
